project:
  type: website

website:
  title: "Yiting"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
  page-footer:
    right: "&copy; 2025, Yiting Wang"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto

